server:
  port: ${ORDER_SERVER_PORT:8086}

spring:
  datasource:
    url: jdbc:postgresql://${ORDER_DB_HOST:postgres_order}:${ORDER_DB_PORT:5432}/${ORDER_DB_NAME:order_db}
    username: ${ORDER_DB_USERNAME:postgres}
    password: ${ORDER_DB_PASSWORD:17052007}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.xml


  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
    consumer:
      group-id: order-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.innowise.*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
    properties:
      retries: 3
      acks: all
      request.timeout.ms: 30000
      delivery.timeout.ms: 45000
      batch.size: 16384
      linger.ms: 5
      compression.type: snappy
    topic:
      order-events: order-events
      payment-events: payment-events


user:
  service:
    url: ${USER_SERVICE_URI:http://user-service:8082}

resilience4j:
  circuitbreaker:
    instances:
      userService:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        automatic-transition-from-open-to-half-open-enabled: true