server:
  port: ${ORDER_SERVER_PORT:8086}

spring:
  datasource:
    url: jdbc:postgresql://${ORDER_DB_HOST:postgres_order}:${ORDER_DB_PORT:5432}/${ORDER_DB_NAME:order_db}
    username: ${ORDER_DB_USERNAME:postgres}
    password: ${ORDER_DB_PASSWORD:17052007}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.xml

# User service URL inside Docker network
user:
  service:
    url: ${USER_SERVICE_URI:http://user-service:8082}

resilience4j:
  circuitbreaker:
    instances:
      userService:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        automatic-transition-from-open-to-half-open-enabled: true
