server:
  port: ${ORDER_SERVER_PORT:8086}

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://${ORDER_DB_HOST:postgres-order}:${ORDER_DB_PORT:5432}/${ORDER_DB_NAME:order_db}
    username: ${ORDER_DB_USERNAME:postgres}
    password: ${ORDER_DB_PASSWORD:17052007}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.xml

  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      timeout: 2000ms


  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    consumer:
      session-timeout-ms: 45000
      heartbeat-interval-ms: 15000
      max-poll-interval-ms: 300000
      max-poll-records: 100
      group-id: order-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.innowise.*"
        spring.json.add.type.headers: true
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: true
    properties:
      retries: 3
      acks: all
      request.timeout.ms: 30000
      delivery.timeout.ms: 45000
      batch.size: 16384
      linger.ms: 5
      compression.type: gzip
    topic:
      order-events: order-events
      payment-events: payment-events


user:
  service:
    url: ${USER_SERVICE_URI:http://user-service:8082}

resilience4j:
  circuitbreaker:
    instances:
      userService:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        automatic-transition-from-open-to-half-open-enabled: true


management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,loggers,env
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
  health:
    circuitbreakers:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name:order-service}
      service: order-service
      environment: ${ENVIRONMENT:dev}
    distribution:
      percentiles-histogram:
        '[http.server.requests]': true
      slo:
        '[http.server.requests]': 50ms,100ms,200ms,400ms,800ms,1s,2s
  observations:
    key-values:
      application: ${spring.application.name}
      service: order-service
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: ${TEMPO_ENDPOINT:http://tempo:4318/v1/traces}
  loki:
    url: ${LOKI_URL:http://loki:3100}
